### PR TITLE
Support ioredis and and provide more options on race condition

### PR DESCRIPTION
**Pull request by nodify-at**
ioredis returns a result set within an array like `result = [ [ERR | null, result] ]`. We need to improve implementation to support ioredis client. I've implemented simple checks to ensure reading correct values.

I've also provided some more options to caller if a race condition occurs: 

* A callback to inform caller that a race condition happens
* An option so caller can decide to immediately delete rate limit entry or like before delete after defined expiration perion

### CODE REVIEW

**Comment by rprieto** [comment]
Hi, thanks for adding support for ioredis. The change looks good :+1:

However most files are changed from being re-indented which makes it hard to see what changed exactly. Could you please undo the chunks not linked to this PR, or maybe change your ESLint config to 2 spaces for example? Thanks

**Comment by nodify-at** [comment]
@rprieto Thanks for your feedback. I've improved and removed whitespaces. Let me please know if you need additional improvements.

**Comment by rprieto** [comment]
Thanks for the changes, it looks perfect! Thanks as well for adding tests for the new client :100:

The only 2 other comments I have (if you want to make another PR) are
- adding a description of the 2 new options in the README
- if the new tests are identical to the old ones, there might be a way to avoid duplicating the file by using something like:

```js
['redis', 'ioredis'].forEach(function(clientName) {
  describe(`Testing client: ${clientName}`, function() {
    let client = require(clientName)
    // then just the same as before
    it('...', ...)
  })
})

**Comment by rprieto** [comment]
Sorry I can't merge yet because the build is failing.
The problem is that the code doesn't run on Node 4. I'm happy to drop support for Node 4. Can you please remove it from `.travis.yml`?

**Comment by nodify-at** [comment]
@rprieto It looks good now. 
I will create another PR for testing improvements incl. an update for read.me

**Comment by nodify-at** [comment]
@rprieto Thanks for approval! When do you plan to publish a new version?

**Comment by deancouch** [comment]
Published 1.2.0 - thanks guys

**Pull request merged**
